### ISSUE TITLE
Data augmentation should change intrinsics

### ISSUE THREAD

**Issue by anandbhoraskar** [YvanYin/VNL_Monocular_Depth_Prediction#48]
The data augmentation involves random cropping. This would leave the focal_x and focal_y values from the NYUV2 and KITTI datasets invalid with error. Especially when we crop with a different aspect ratio than 1:1
Is there a reason why the method is robust to this incorrect fx/fy ratio?

**Comment by YvanYin** [comment]
Hi, when I train the model, I will scale the focal length with the resizing ratio. It will not cause an invalid value. Could you describe the problem in more detail?

**Comment by anandbhoraskar** [comment]
Hello. Thanks for responding.
I was looking at the functions `set_flip_pad_reshape_crop` and `flip_pad_reshape_crop` in data/kitti_dataset.py
These are the locations where the images are augmented but the intrinsics are not changed.

**Comment by YvanYin** [comment]
Hi,  my previous answer may confuse you. When I do the resizing augmentation, I will just scale the depth instead of focal length. When I enlarge the image, the objects in the image will be larger in the cropped region. It means this object will be closer. Therefore, when resizing the image the depth map will be scaled at the same time.

**Comment by anandbhoraskar** [comment]
I was actually referring to the fx and fx of the intrinsic matrix, which is 519 for the dataset.
That would no longer be valid after we rescale it.

**Comment by YvanYin** [comment]
You don't need to change the focal length. I used the original focal length of the dataset when doing the augamentation.
